services:
  - type: web
    name: umico-dashboard-backend
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium && playwright install-deps chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: STORE_1_NAME
        value: Shark Electronics
      - key: STORE_1_USERNAME
        value: 994505729228-5137
      - key: STORE_1_PASSWORD
        value: ub7ztQnd
      - key: STORE_2_NAME
        value: Shahin Electronics
      - key: STORE_2_USERNAME
        value: 994505729228-4212
      - key: STORE_2_PASSWORD
        value: eq1S7az8
      - key: STORE_3_NAME
        value: AZERRA
      - key: STORE_3_USERNAME
        value: 994505729228-9039
      - key: STORE_3_PASSWORD
        value: CKRD6JtR
      - key: STORE_4_NAME
        value: FANTOM
      - key: STORE_4_USERNAME
        value: 994505729228-9038
      - key: STORE_4_PASSWORD
        value: iQ6FDzPq
      - key: STORE_5_NAME
        value: Duvel Electronics
      - key: STORE_5_USERNAME
        value: 994705020887-12372
      - key: STORE_5_PASSWORD
        value: 4UgXkdET
      - key: STORE_6_NAME
        value: KUKMARA
      - key: STORE_6_USERNAME
        value: 994505729228-9024
      - key: STORE_6_PASSWORD
        value: uQfUvRw3
